### ISSUE TITLE
Doesn't stay authenticated

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress-pro-gdrive#38]
Seems like Google Drive periodically looses authentication. 

Initial guess could be that there's a time limit on the Google Drive auth token or something along those limes

**Comment by pdewouters** [comment]
Yes I think you're right. Needs investigating to see if we can make it permanent

**Comment by pdewouters** [comment]
might be an issue with refresh token http://stackoverflow.com/a/23626945

**Comment by owaincuvelier** [comment]
Bit of pressure to get this fixed asap.

**Comment by pdewouters** [comment]
@owaincuvelier does this still happen with the latest version?

**Comment by pdewouters** [comment]
can't reproduce this, stays authenticated with latest version

**Comment by owaincuvelier** [comment]
@pdewouters seems to happen still on the 2.1.2 beta: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/937280012

**Comment by pdewouters** [comment]
@willmot is the Google drive app registered as "installed application"?
https://developers.google.com/drive/web/auth/web-server

**Comment by pdewouters** [comment]
This was in the error log on betabwp

```
[22-Jun-2015 10:51:10 UTC] PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling GET https://www.googleapis.com/drive/v2/files?q=mimeType+%3D+%27application%2Fvnd.google-apps.folder%27: (401) Login Required' in /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.php:110
Stack trace:
#0 /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Task/Runner.php(174): call_user_func_array(Array, Array)
#3 /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.p in /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.php on line 110
[23-Jun-2015 09:44:29 UTC] PHP Fatal error:  Uncaught exception 'Google_Service_Exception' with message 'Error calling GET https://www.googleapis.com/drive/v2/files?q=mimeType+%3D+%27application%2Fvnd.google-apps.folder%27: (401) Login Required' in /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.php:110
Stack trace:
#0 /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 [internal function]: Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))
#2 /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Task/Runner.php(174): call_user_func_array(Array, Array)
#3 /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.p in /home/pauldewouters/betabwp.humanmade.co.uk/wp-content/plugins/backupwordpress-pro-gdrive/vendor/google/apiclient/src/Google/Http/REST.php on line 110

```

**Comment by pdewouters** [comment]
ok I found the issue that the authentication setting gets deleted. I will issue a fix later today

**Comment by pdewouters** [comment]
@owaincuvelier I uploaded a test version with a fix for authentication under /auth-fix/ in the google drive folder.
this will need to be applied to othe other addons too

**Comment by pdewouters** [comment]
Fixed
